INSERT INTO categories (category_id, category_name)
VALUES 
('Moda> Kadın> Elbise'),
('Moda> Kadın> Triko&Kazak'),
('Moda> Kadın> Mont Kaban'),
('Moda> Kadın> Sweatshirt'),
('Moda> Kadın> Pantolon'),
('Moda> Kadın> Ayakkabı'),
('Moda> Erkek> T-shirt'),
('Moda> Erkek> Sweatshirt'),
('Moda> Erkek> Gömlek'),
('Moda> Erkek> Eşofman'),
('Moda> Erkek> Pantolon'),
('Moda> Erkek> Mont&Kaban'),
('Moda> Erkek> Ayakkabı'),
('Moda> Kız Çocuk> Elbise'),
('Moda> Kız Çocuk> T-shirt'),
('Moda> Kız Çocuk> Sweatshirt'),
('Moda> Kız Çocuk> Tayt'),
('Moda> Kız Çocuk> Eşofman'),
('Moda> Kız Çocuk> Pantolon'),
('Moda> Kız Çocuk> Ayakkabı'),
('Moda> Erkek Çocuk> T-shirt'),
('Moda> Erkek Çocuk> Sweatshirt'),
('Moda> Erkek Çocuk> Gömlek'),categoriescategories
('Moda> Erkek Çocuk> Eşofman'),
('Moda> Erkek Çocuk> Pantolon'),
('Moda> Erkek Çocuk> Ayakkabı'),
('Elektronik> Bilgisayar&Tablet> Dizüstü Bilgisayar'),
('Elektronik> Bilgisayar&Tablet> Masaüstü Bilgisayar'),
('Elektronik> Bilgisayar&Tablet> Tablet'),
('Elektronik> Telefon&Telefon Aksesuarları> Cep Telefonu'),
('Elektronik> Telefon&Telefon Aksesuarları> Akıllı Saatler'),
('Elektronik> Telefon&Telefon Aksesuarları> Aksesuarlar'),
('Elektronik> Foto&Kamera> Dijital Fotoğraf'),
('Elektronik> Foto&Kamera> Video Kameralar'),
('Elektronik> Foto&Kamera> Aksiyon Kamerası'),
('Elektronik> Beyaz Eşya> Buzdolabı'),
('Elektronik> Beyaz Eşya> Bulaşık Makinası'),
('Elektronik> Beyaz Eşya> Çamaşır Makinası'),
('Elektronik> Oyuncu Ekipmanları> Kulaklık'),
('Elektronik> Oyuncu Ekipmanları> Klavye'),
('Elektronik> Oyuncu Ekipmanları> Mouse'),
('Spor Outdoor> Spor Ayakkabı'),
('Spor Outdoor> Fitness Kondisyon'),
('Spor Outdoor> Kampçılık Ekipmanları'),
('Spor Outdoor> Şişme Su Ürünleri'),
('Anne, Bebek, Oyuncak> Anne&Bebek> Bebek Giyim'),
('Anne, Bebek, Oyuncak> Anne&Bebek> Bebek Maması'),
('Anne, Bebek, Oyuncak> Anne&Bebek> Bebek Bezi'),
('Anne, Bebek, Oyuncak> Oyuncak> Bebek Oyuncakları'),
('Anne, Bebek, Oyuncak> Oyuncak> Kız Çocuk Oyuncakları'),
('Anne, Bebek, Oyuncak> Oyuncak> Erkek Çocuk Oyuncakları'),
('Kozmetik, Kişisel Bakım> Parfüm> Erkek Parfüm'),
('Kozmetik, Kişisel Bakım> Parfüm> Kadın Parfüm'),
('Kozmetik, Kişisel Bakım> Parfüm> Lüks Parfüm'),
('Kozmetik, Kişisel Bakım> Makyaj> Maskara'),
('Kozmetik, Kişisel Bakım> Makyaj> Fondöten'),
('Kozmetik, Kişisel Bakım> Makyaj> Eyeliner'),
('Kozmetik, Kişisel Bakım> Makyaj> Ruj'),
('Kozmetik, Kişisel Bakım> Makyaj> Kapatıcı'),
('Kozmetik, Kişisel Bakım> Bakım> Cild Bakımı'),
('Kozmetik, Kişisel Bakım> Bakım> Ağız Bakımı'),
('Kozmetik, Kişisel Bakım> Bakım> Saç Bakımı'),
('Kozmetik, Kişisel Bakım> Bakım> Epilasyon&Ağda'),
('Ev,Mobilya,Kırtasiye> Ev Tekstili> Nevresim'),
('Ev,Mobilya,Kırtasiye> Ev Tekstili> Yorgan'),
('Ev,Mobilya,Kırtasiye> Ev Tekstili> Yastık'),
('Ev,Mobilya,Kırtasiye> Ev Tekstili> Halı&Kilim'),
('Ev,Mobilya,Kırtasiye> Ev Tekstili> Perde'),
('Ev,Mobilya,Kırtasiye> Mobilya> Koltuk Takımları'),
('Ev,Mobilya,Kırtasiye> Mobilya> Masa Sandalye Takımları'),
('Ev,Mobilya,Kırtasiye> Mobilya> Dolap Takımları'),
('Ev,Mobilya,Kırtasiye> Mobilya> Yatak Odası Takımları'),
('Ev,Mobilya,Kırtasiye> Mobilya> Çalışma Masası'),
('Ev,Mobilya,Kırtasiye> Kırtasiye> Kitap&Defter'),
('Ev,Mobilya,Kırtasiye> Kırtasiye> Kalem&Boyama Kalemleri'),
('Ev,Mobilya,Kırtasiye> Kırtasiye> Ofis Sarf Malzemeleri'),
('Ev,Mobilya,Kırtasiye> Kırtasiye> Fotokobi Kağıtları');